apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-svc-deploy
  labels:
    app: healthcare-svc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-svc-app
  template:
    metadata:
      labels:
        app: healthcare-svc-app
    spec:
      containers:
      - name: healthcare-svc-container
        image: vidyashree2002/healthcare-svc-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-svc-np-service
  labels:
    app: healthcare-svc-app
spec:
  selector:
    app: healthcare-svc-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
